### ISSUE TITLE
Alternative PSU issue

### ISSUE THREAD

**Issue by AidenShaw2020** [fust/T1600-PSU#2]
Hi Fust, i need technical help.

I got it T1600/40 without PSU (respectively, from PSU was remained only connector to MB.

I created replacement PSU from buck step converters, with this assigments:

9,10,11,14 - positive 12V
13,15 - positive 5V
17 - negative 22V
27,29,30,31,33,34,35 - positive 5V
39,41 - positive 12V
49 - negative 9V
50 - positive 12V

Without connected LCD screen, i got after some seconds post beep, but when i connect LCD, i get short circuit.

When i disconnect negative 9V, i dont get short circuit, but computer not post, and power consumption raised about 40mA, and LCD backlight is dark.

Can you help me with this? Thanks.

**Comment by fust** [comment]
First thing I'd suggest is to check if the LCD has a short on one of it's power rails.
The pinout can be found in the service manual on minuszerodegrees.net (See Appendix A of the troubleshooting guide for a direct link).
Secondly, verify you're using the correct pins on the PSU connector. The pinout is not very intuitive and I've not done a great job of representing it in the schematic.
The connector used is a 50 pin KEL 8800 series or 3M P50 series, datasheet can be found here: https://docs.rs-online.com/dad0/0900766b8153aeae.pdf

If you have access to a monitor capable of accepting EGA signals it's worth a try to connect the external display port to it to verify the system itself is working correctly and it's only the LCD causing issues.
As far as I'm aware the -9V and -22V shouldn't be necessary to power the system and allow it to post, they're only used for the RS232 and LCD, respectively.
The system is mostly TTL logic and should, apart from the harddrive spindle motor, work on just the +5V rails.

**Comment by AidenShaw2020** [comment]
Hi Fust, after some time, i buy mce2hdmi, and now i got further info.

Computer its starts, but i got two error messages.

1st: Error in CMOS. Bad baterry. Check system. Than press any key

2nd: Error in CMOS. Bad check sum. Check system. Than press any key

If i press any key on 1st message i got second, but on second i stuck.

CMOS battery is changed.

Any sugestions? Thanks.

**Comment by fust** [comment]
Could be a number of things unfortunately.

IIRC the machine shows these errors after the memory check is performed, please correct me if I'm wrong.

If that is indeed the case make sure the HDD and FDD are connected properly. The BIOS will wait (a very long time) for the HDD to respond before trying to boot from FDD is it's not connected.
I'm not sure what happens if the FDD isn't connected but I'd imagine it would just show a missing disk message.

Next make sure there is no trace damage on the motherboard, it could be the CMOS IC isn't able to talk to the rest of the system.
If that is all looking good I'd be suspecting a fault in the CMOS IC but I can't say for sure.

A parallel port diagnostics adapter can be helpful here and is easily constructed: Get a DB25 connector, 8 LEDs and a 220 Ohm resistor. The anode of the LEDs connects to the 8 data bits on the parallel port, the cathode to the resistor which in turn connects to ground.
The T-series machines all output diagnostic codes to the parallel port from the BIOS, a table mapping the codes to error descriptions can be found on page 2-9 of the T1600 maintenance manual.

**Comment by AidenShaw2020** [comment]
You're absolutely right. After a few minutes it moved and I finished the boot :)

Now I just have to sort out the non-functioning hard reset, the (most likely) short in the LCD and the hdd replacement :)

Thanks.

**Comment by fust** [comment]
The electronics side is probably very manageable.
The HDD replacement is a whole other story as these machines are _extremely_ picky on which drives they accept.
Fortunately there is a solution to that based on the XT-IDE BIOS.
It is built by a viewer of mine for who I repaired 2 PSU boards. He also built some with additional goodies on board but they seem to be sold out at the moment.

This is the link to his ebay product page: https://www.ebay.nl/itm/266393919760?mkcid=16&mkevt=1&mkrid=1346-175129-2357-0&ssspo=7O4PhbOZTTi&sssrc=4429486&ssuid=mx2Vf7G8Ry6&var=566208849026&widget_ver=artemis&media=COPY

**Comment by AidenShaw2020** [comment]
Hi Fust, i have progress. Shortcircuit has resolved, and lcd is turned on, but its seems broken (doesnt show anything, only some line artefacts, when i switch to CRT. Any suggestions to check? 

Many thanks :)
![IMG_1706](https://github.com/fust/T1600-PSU/assets/62829872/7a83214d-3851-44f7-9799-6098b4eb46ca)
![IMG_1708](https://github.com/fust/T1600-PSU/assets/62829872/fbf9e3b6-c386-4c3b-b766-d4bea8f9fd14)
![IMG_1709](https://github.com/fust/T1600-PSU/assets/62829872/65ffa1d1-17bd-440f-a4a4-6fb3eaf196fa)
![IMG_1710](https://github.com/fust/T1600-PSU/assets/62829872/ee8232a4-2c9a-41e4-8b85-f2fa36d1a234)
![IMG_1711](https://github.com/fust/T1600-PSU/assets/62829872/9c747159-6595-4906-9f2e-1b66c9981b91)

**Comment by AidenShaw2020** [comment]
Addendum: Caps is replaced.

**Comment by fust** [comment]
Hard to say what's going on exactly.
Since the machine is outputting to an external monitor a major part of the video circuitry works.
The artifacts seem to indicate that the LCD is receiving the negative voltage it needs for contrast adjustment and that the contrast is set to a somewhat reasonable value or nothing would show up.
I'd start by checking the cable and connectors from the motherboard to the LCD board for continuity.
If that looks good it's time to start probing the signals with an oscilloscope, the pinout of the LCD connector should be in the maintenance manual.
It could also be that the LCD (the driver ICs in particulat) has taken more damage from whatever caused the short-circuit.
